/* global systemDictionary: true */
"use strict";

systemDictionary = {
    "rssfeed adapter settings": {
        "en": "Adapter settings for rssfeed",
        "de": "Adaptereinstellungen für rssfeed",
        "ru": "Настройки адаптера для rssfeed",
        "pt": "Configurações do adaptador para rssfeed",
        "nl": "Adapterinstellingen voor rssfeed",
        "fr": "Paramètres d'adaptateur pour rssfeed",
        "it": "Impostazioni dell'adattatore per rssfeed",
        "es": "Ajustes del adaptador para rssfeed",
        "pl": "Ustawienia adaptera dla rssfeed",
        "zh-cn": "rssfeed的适配器设置"
    },
    "rss_oid": {
        "en": "RSS data point",
        "de": "RSS-Datenpunkt",
        "ru": "Точка данных RSS",
        "pt": "Ponto de dados RSS",
        "nl": "RSS-gegevenspunt",
        "fr": "Point de données RSS",
        "it": "Punto dati RSS",
        "es": "Punto de datos RSS",
        "pl": "Punkt danych RSS",
        "uk": "Точка даних RSS",
        "zh-cn": "RSS 数据点"
    },
    "rss_template": {
        "en": "RSS Template",
        "de": "RSS Vorlage",
        "ru": "Шаблон RSS",
        "pt": "Modelo de RSS",
        "nl": "RSS-sjabloon",
        "fr": "Modèle RSS",
        "it": "Template RSS",
        "es": "Plantilla RSS",
        "pl": "Wzór RSS",
        "uk": "Шаблони RSS",
        "zh-cn": "RSS 模板"
    },
    "rss_maxarticles": {
        "en": "RSS max. articles",
        "de": "RSS max. Artikel",
        "ru": "RSS макс. статьи",
        "pt": "RSS max. artigos",
        "nl": "RSS max. artikelen",
        "fr": "Articles RSS max",
        "it": "RSS max. articoli",
        "es": "RSS max. artículos",
        "pl": "RSS max. article",
        "uk": "Статті RSS",
        "zh-cn": "RSS 最多的文章"
    },
    "rss_filter": {
        "en": "RSS Filter",
        "de": "RSS Filter",
        "ru": "Фильтр RSS",
        "pt": "Filtro de RSS",
        "nl": "RSS-filter",
        "fr": "Filtre RSS",
        "it": "Filtro RSS",
        "es": "Filtro RSS",
        "pl": "Filtr RSS",
        "uk": "RSS фільтр",
        "zh-cn": "RSS 过滤器"
    },
    "rss_feedCount": {
        "en": "RSS Feed Number",
        "de": "RSS Feed Nummer",
        "ru": "Номер RSS",
        "pt": "Número de feed RSS",
        "nl": "RSS-feednummer",
        "fr": "Numéro de flux RSS",
        "it": "Numero di feed RSS",
        "es": "Número de alimentación RSS",
        "pl": "Numer RSS",
        "uk": "RSS-канал",
        "zh-cn": "RSS 种子编号"
    },
    "rss_dpCount": {
        "en": "RSS Data Point Count",
        "de": "RSS Anzahl der Punkte",
        "ru": "RSS Количество точек данных",
        "pt": "RSS Contagem de Pontos de Dados",
        "nl": "RSS Aantal gegevenspunten",
        "fr": "Autres Nombre de points de données",
        "it": "RSS Contatore di punti dati",
        "es": "RSS Cuenta de Puntos de Datos",
        "pl": "RSS Liczba punktów danych",
        "uk": "Про нас Кількість точок даних",
        "zh-cn": "简易新闻聚合 数据点数"
    },
    "rss_dp": {
        "en": "RSS data point",
        "de": "RSS-Datenpunkt",
        "ru": "Точка данных RSS",
        "pt": "Ponto de dados RSS",
        "nl": "RSS-gegevenspunt",
        "fr": "Point de données RSS",
        "it": "Punto dati RSS",
        "es": "Punto de datos RSS",
        "pl": "Punkt danych RSS",
        "uk": "Точка даних RSS",
        "zh-cn": "RSS 数据点"
    },
    "rss_name": {
        "en": "RSS Name",
        "de": "RSS Name",
        "ru": "RSS Имя",
        "pt": "RSS Nome",
        "nl": "RSS Naam",
        "fr": "Autres Dénomination",
        "it": "RSS Nome",
        "es": "RSS Nombre",
        "pl": "RSS Nazwa",
        "uk": "Про нас Ім'я",
        "zh-cn": "简易新闻聚合 名称"
    },
    "group_feeds": {
        "en": "RSS Feed Group",
        "de": "RSS Feed Group",
        "ru": "RSS Feed Group",
        "pt": "Grupo de alimentação RSS",
        "nl": "RSS Feed Group",
        "fr": "Groupe de flux RSS",
        "it": "Gruppo RSS",
        "es": "Grupo de alimentación RSS",
        "pl": "RSS Feed Group",
        "uk": "RSS Feed Group",
        "zh-cn": "RSS 种子组"
    },
    "rss_prefix": {
        "en": "RSS Prefix",
        "de": "RSS Prefix",
        "ru": "Префикс RSS",
        "pt": "RSS Prefixação",
        "nl": "RSS-voorvoegsel",
        "fr": "Préfixe RSS",
        "it": "Prefisso RSS",
        "es": "Prefijo RSS",
        "pl": "Prefiks RSS",
        "uk": "Преса",
        "zh-cn": "RSS 前缀"
    },
    "rss_article": {
        "en": "RSS Article count",
        "de": "RSS Artikelanzahl",
        "ru": "RSS Количество статей",
        "pt": "RSS Contagem de artigos",
        "nl": "RSS Aantal artikelen",
        "fr": "Autres Nombre d'articles",
        "it": "RSS Articolo",
        "es": "RSS Artículo contado",
        "pl": "RSS Liczba artykułów",
        "uk": "Про нас Кількість статей",
        "zh-cn": "简易新闻聚合 文章计数"
    },
    "rss_speed": {
        "en": "RSS Speed",
        "de": "RSS Geschwindigkeit",
        "ru": "RSS Скорость",
        "pt": "RSS Velocidade",
        "nl": "RSS Snelheid",
        "fr": "Autres Vitesse",
        "it": "RSS Velocità",
        "es": "RSS Speed",
        "pl": "RSS Prędkość",
        "uk": "Про нас Швидкість",
        "zh-cn": "简易新闻聚合 速度"
    },
    "rss_divider": {
        "en": "RSS Seperator",
        "de": "RSS Separator",
        "ru": "RSS Seperator",
        "pt": "RSS Seperador",
        "nl": "RSS-afscheider",
        "fr": "Séperateur RSS",
        "it": "Seperatore RSS",
        "es": "Seperator RSS",
        "pl": "Seperator RSS",
        "uk": "Сепаратор новин",
        "zh-cn": "RSS 剪辑器"
    },
    "rss_pauseonhover": {
        "en": "RSS Pause on hover",
        "de": "RSS Pause beim Hover",
        "ru": "RSS Pause on hover",
        "pt": "RSS Pausa no rio",
        "nl": "RSS Pauzeer bij zweven",
        "fr": "Autres Pause en vol stationnaire",
        "it": "RSS Pausa su hover",
        "es": "RSS Pausa en la palanca",
        "pl": "RSS Pauza na huśtawce",
        "uk": "Про нас Пауза на конюшині",
        "zh-cn": "简易新闻聚合 暂停悬浮"
    },
    "rss_link": {
        "en": "RSS Link",
        "de": "RSS Link",
        "ru": "RSS Ссылка",
        "pt": "RSS Link",
        "nl": "RSS Verband",
        "fr": "Autres Lien",
        "it": "RSS Link",
        "es": "RSS Enlace",
        "pl": "RSS Związek",
        "uk": "Про нас Посилання",
        "zh-cn": "简易新闻聚合 链接"
    },
    "rss_withtime": {
        "en": "RSS with time",
        "de": "RSS mit Zeit",
        "ru": "RSS со временем",
        "pt": "RSS com o tempo",
        "nl": "RSS met tijd",
        "fr": "RSS avec le temps",
        "it": "RSS con il tempo",
        "es": "RSS con el tiempo",
        "pl": "RSS z czasem",
        "uk": "Час",
        "zh-cn": "有时间的RSS"
    },
    "json_oid": {
        "en": "JSON data point",
        "de": "JSON Datenpunkt",
        "ru": "Точка данных JSON",
        "pt": "Ponto de dados JSON",
        "nl": "JSON-gegevenspunt",
        "fr": "Point de données JSON",
        "it": "Punto dati JSON",
        "es": "Punto de datos JSON",
        "pl": "Punkt danych JSON",
        "uk": "Точка даних JSON",
        "zh-cn": "JSON 数据点"
    },
    "json_template": {
        "en": "JSON Template",
        "de": "JSON Vorlage",
        "ru": "JSON Template",
        "pt": "Modelo JSON",
        "nl": "JSON-sjabloon",
        "fr": "Modèle JSON",
        "it": "Template JSON",
        "es": "Plantilla JSON",
        "pl": "Szablon JSON",
        "uk": "Шаблон JSON",
        "zh-cn": "JSON 模板"
    }
};
